close all;
clear all;
clc;

load -ASCII RESOLUTION_DATA_PENCIL_XDIR_MATLAB.dat
NX = 512

FFT_DATA(:,1) = RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,1);
FFT_DATA(:,2) = RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,9).^2 + RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,10).^2 + RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,11).^2;
FFT_DATA(:,3) = RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,12).^2 + RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,13).^2 + RESOLUTION_DATA_PENCIL_XDIR_MATLAB(1:NX,14).^2;
%nk = 500;
  

fid = fopen('FFT_DATA.dat','w');



    
for k = 1:NX

fprintf(fid,'%f    %.15f    %.15f \n',FFT_DATA(k,1),FFT_DATA(k,2), FFT_DATA(k,3) );

end; 
